rocket_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rocket_shoulder_pan_joint
    - rocket_shoulder_lift_joint
    - rocket_elbow_joint
    - rocket_wrist_1_joint
    - rocket_wrist_2_joint
    - rocket_wrist_3_joint
  gains:
    rocket_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rocket_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rocket_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rocket_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rocket_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rocket_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
groot_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - groot_shoulder_pan_joint
    - groot_shoulder_lift_joint
    - groot_elbow_joint
    - groot_wrist_1_joint
    - groot_wrist_2_joint
    - groot_wrist_3_joint
  gains:
    groot_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    groot_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    groot_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    groot_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    groot_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    groot_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
rocket_and_groot_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - groot_shoulder_pan_joint
    - groot_shoulder_lift_joint
    - groot_elbow_joint
    - groot_wrist_1_joint
    - groot_wrist_2_joint
    - groot_wrist_3_joint
    - rocket_shoulder_pan_joint
    - rocket_shoulder_lift_joint
    - rocket_elbow_joint
    - rocket_wrist_1_joint
    - rocket_wrist_2_joint
    - rocket_wrist_3_joint
  gains:
    groot_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    groot_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    groot_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    groot_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    groot_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    groot_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rocket_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rocket_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rocket_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rocket_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rocket_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rocket_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1